<?php

/**
 * This is the model base class for the table "clearmind".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Clearmind".
 *
 * Columns in table "clearmind" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property integer $user_id
 * @property string $root
 * @property string $lft
 * @property string $rgt
 * @property integer $level
 * @property string $node_title
 * @property string $node_content
 *
 */
abstract class BaseClearmind extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'clearmind';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Clearmind|Clearminds', $n);
	}

	public static function representingColumn() {
		return 'node_title';
	}

	public function rules() {
		return array(
			array('user_id, lft, rgt, level, node_title, node_content', 'required'),
			array('user_id, level', 'numerical', 'integerOnly'=>true),
			array('root, lft, rgt', 'length', 'max'=>10),
			array('root', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, root, lft, rgt, level, node_title, node_content', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'root' => Yii::t('app', 'Root'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'node_title' => Yii::t('app', 'Node Title'),
			'node_content' => Yii::t('app', 'Node Content'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('root', $this->root, true);
		$criteria->compare('lft', $this->lft, true);
		$criteria->compare('rgt', $this->rgt, true);
		$criteria->compare('level', $this->level);
		$criteria->compare('node_title', $this->node_title, true);
		$criteria->compare('node_content', $this->node_content, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}